{% set name = "mesonlsp" %}
{% set version = "4.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JCWasmx86/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b84b2d4060a1aa0e09161f1a30e55f1a4d007609813e284ed4b0f4f969d406fa

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
    - sed  # [unix]
  host:
    - libarchive
    - libcurl
    - fmt  # [osx]
    - lsprotocol
    - nlohmann_json
    - pkgconf
    - pygls
    - libuuid
    - zlib

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/JCWasmx86/{{ name }}
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: An unofficial, unendorsed language server for meson written in C++
  dev_url: https://github.com/JCWasmx86/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
